### ISSUE TITLE
rtmp推流rtc播放时, http hooks 收到的 app steam 不一致

### ISSUE THREAD

**Issue by xupeng1206** [ossrs/srs#2797] opened 2021-12-17 07:04 UTC
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 当推流地址形如 rtmp://dev-stream.turingvideo.cn:1935/live/436/387236c7d1f4112c4b7d9580cdb047f0时, webrtc播放的时候，on_connect, on_play, on_stop 收到的数据中app及stream不一致。

> on_connect中 app=live  stream=436/387236c7d1f4112c4b7d9580cdb047f0

> on_play及on_stop中  app=live/436  stream=387236c7d1f4112c4b7d9580cdb047f0

1. SRS版本(Version):  4.0-Release

1. SRS的日志如下(Log):
![image](https://user-images.githubusercontent.com/30151441/146502626-0b82c773-c33a-4573-92d9-b0c577d825e7.png)

1. SRS的配置如下(Config):
```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     10000;
srs_log_tank        console;
daemon              off;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
rtc_server {
    enabled         on;
    # Listen at udp://8000
    listen          8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
    candidate       $CANDIDATE;
}
vhost __defaultVhost__ {
    tcp_nodelay     on
    min_latency     on;

    hls {
        enabled         off;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        bframe      discard;
        rtmp_to_rtc on;
        rtc_to_rtmp off;
    }
    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      0;
    }

    publish {
        mr off;
        # mr_latency 100;
        normal_timeout 600000;
    }

    http_hooks{
        enabled       on;
        # 172.18.0.3 => srs_hook container ip
        on_connect    http://172.18.0.3:8085/api/srs/hooks/connect;
        on_close      http://172.18.0.3:8085/api/srs/hooks/close;
        # on_publish    http://172.18.0.3:8085/api/srs/hooks/publish;
        # on_unpublish  http://172.18.0.3:8085/api/srs/hooks/unpublish;
        on_play       http://172.18.0.3:8085/api/srs/hooks/play;
        on_stop       http://172.18.0.3:8085/api/srs/hooks/stop;
        # on_dvr        http://172.18.0.3:8085/api/srs/hooks/dvr;
        # on_hls        http://172.18.0.3:8085/api/srs/hooks/hls;
        # on_hls_notify http://172.18.0.3:8085/api/srs/hooks/hls_notify;
    }
}

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. ffmpeg 推流到形如 rtmp://dev-stream.turingvideo.cn:1935/live/436/387236c7d1f4112c4b7d9580cdb047f0 的地址。
2. webrtc播放流，播放地址：webrtc://dev-stream.turingvideo.cn/live/436/387236c7d1f4112c4b7d9580cdb047f0。
3. 查看srs日志即复现。

**期望行为(Expect)**

> 期望rtmp推流rtc播放时候，on_connect on_play on_stop 中，app stream 等信息一致。

**Comment by xupeng1206** [comment] 2021-12-17 07:32
Try to fix it yourself: https://github.com/ossrs/srs/pull/2798
Not sure if the changes are correct.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2021-12-17 23:49
According to our simplified definition, we only support multi-level apps, not multi-level streams.

If the URL is:

```
rtmp://dev-stream.turingvideo.cn:1935/live/436/387236c7d1f4112c4b7d9580cdb047f0
```

Then it should be:

```
schema: rtmp
host: dev-stream.turingvideo.cn
port: 1935
app: live/436
stream: 387236c7d1f4112c4b7d9580cdb047f0
```

It is equivalent to our belief that directories can have multiple levels, while files do not support multiple levels.

`TRANS_BY_GPT3`

**Comment by xupeng1206** [comment] 2021-12-20 01:47
> According to our simplified definition, we only support multi-level apps and do not support multi-level streams.
> 
> If the URL is:
> 
> ```
> rtmp://dev-stream.turingvideo.cn:1935/live/436/387236c7d1f4112c4b7d9580cdb047f0
> ```
> 
> Then it should be:
> 
> ```
> schema: rtmp
> host: dev-stream.turingvideo.cn
> port: 1935
> app: live/436
> stream: 387236c7d1f4112c4b7d9580cdb047f0
> ```
> 
> It means that we believe directories can have multiple levels, while files do not support multiple levels.

If that's the case, then the PR I mentioned earlier would be problematic. I'll wait for the API expert to take a look. Thank you.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment] 2022-01-09 04:47
> 

Test with the URL you provided, on_connect/play/stop, the app and stream are the same. And as the author said, the app supports hierarchy, while the stream does not. So your PR may not be merged.

`TRANS_BY_GPT3`

**Closed by duiniuluantanqin** 2022-01-09 04:47 UTC

**Comment by xupeng1206** [comment] 2022-01-14 03:05
> > 
> 
> Test with the URL you provided, on_connect/play/stop, the app and stream are the same. And as the author said, the app supports hierarchy, while the stream does not. So your PR may not be merged.

Sorry for the inconvenience, I tested again just now. In the on_connect function, I still get app=live and stream=123/uuid. According to the design, it should be app=live/123 and stream=uuid. There seems to be a discrepancy between the result and the design. I tested with the latest code from the 4.0 Release, commit 0dd6246c2fcacc7650b5b7615a077c1ceb0ea9d2 @duiniuluantanqin.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2022-01-14 03:48
这个是因为你编码器的原因，你一直没说用的什么推流的，参数是什么。

**Comment by winlinvip** [comment] 2022-01-14 04:02
Unable to reproduce the issue you mentioned, for example, the app is `live/live`, and the stream is `livestream`.

SRS configuration:
```
    http_hooks {
        enabled         on;
        on_connect      http://127.0.0.1:8085/api/v1/clients;
        on_publish      http://127.0.0.1:8085/api/v1/streams;
    }
```

Streaming:
```
ffmpeg -re -i doc/source.flv -c copy -f flv rtmp://localhost/live/live/stream
```

SRS Log:
```
client identified, type=fmle-publish, vhost=localhost, app=live/live, stream=stream, param=, duration=0ms
```

Callback Log:
```
srs on_connect: vhost=__defaultVhost__, app=live/live, tcUrl=rtmp://localhost:1935/live/live, pageUrl=

srs on_publish: vhost=__defaultVhost__, app=live/live, stream=stream, param=
```

`TRANS_BY_GPT3`

**Comment by xupeng1206** [comment] 2022-01-17 02:37
> Unable to reproduce the issue you mentioned, for example, the app is `live/live`, and the stream is `livestream`.
> 
> SRS configuration:
> 
> ```
>     http_hooks {
>         enabled         on;
>         on_connect      http://127.0.0.1:8085/api/v1/clients;
>         on_publish      http://127.0.0.1:8085/api/v1/streams;
>     }
> ```
> 
> Push streaming:
> 
> ```
> ffmpeg -re -i doc/source.flv -c copy -f flv rtmp://localhost/live/live/stream
> ```
> 
> SRS log:
> 
> ```
> client identified, type=fmle-publish, vhost=localhost, app=live/live, stream=stream, param=, duration=0ms
> ```
> 
> Callback log:
> 
> ```
> srs on_connect: vhost=__defaultVhost__, app=live/live, tcUrl=rtmp://localhost:1935/live/live, pageUrl=
> 
> srs on_publish: vhost=__defaultVhost__, app=live/live, stream=stream, param=
> ```

- Thank you to all the teachers for their time. In the end, it was found that the streaming tool was the cause. After changing the version of ffmpeg and streaming, it matched the description provided by the author.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2022-01-17 02:56
Thank you for confirming and providing feedback, @xupeng1206.

Thank you, Haibo, for investigating together, @duiniuluantanqin.

`TRANS_BY_GPT3`
