### ISSUE TITLE
SOURCE: http_api streams和clients接口返回的cid不一致

### ISSUE THREAD

**Issue by idxa** [ossrs/srs#591] opened 2016-04-20 07:44 UTC
发现一个问题，现调用`http://10.226.64.66:1985/api/v1/streams/2980`，返回
{"code":0,"server":2976,"stream":{"id":2980,"name":"test_srs","vhost":2977,"app":"myapp","live_ms":1461137754141,"clients":1,"send_bytes":584714058,"recv_bytes":406690402,"kbps":{"recv_30s":0,"send_30s":0},"publish":{"active":false,"cid":221},"video":null,"audio":null}}
显示的cid是221

但查看具体的clients的时候，调用`http://10.226.64.66:1985/api/v1/clients/`，返回
{"code":0,"server":2976,"clients":[{"id":259,"vhost":2977,"stream":2980,"ip":"10.226.64.165","pageUrl":"","swfUrl":"","tcUrl":"rtmp://10.226.64.66/myapp","url":"/myapp/test_srs","type":"fmle-publish","publish":true,"alive":2723442}]}
实际的cid是259

中间推流程序有重启，看上去像stream没有同步更新，使用的是release2.0版本，谢谢！

**Comment by winlinvip** [comment] 2017-02-10 00:20
Unable to reproduce, I see that it has been updated on my end.

`TRANS_BY_GPT3`

**Comment by ivantw08** [comment] 2018-10-01 03:52
Hello, I have the same problem when transcoding. According to the official example, the livestream can be played, but there is an issue with livestream_ff.
{"code":0,"server":29675,"streams":[{"id":29677,"name":"livestream","vhost":29676,"app":"live","live_ms":1538365769216,"clients":1,"frames":28443,"send_bytes":1634774,"recv_bytes":42488949,"kbps":{"recv_30s":358,"send_30s":0},"publish":{"active":true,"cid":109},"video":{"codec":"H264","profile":"High","level":"3.1"},"audio":{"codec":"AAC","sample_rate":44100,"channel":2,"profile":"LC"}},{"id":29678,"name":"livestream_ff","vhost":29676,"app":"live","live_ms":1538365769216,"clients":0,"frames":0,"send_bytes":4298,"recv_bytes":3492,"kbps":{"recv_30s":0,"send_30s":0},"publish":{"active":false,"cid":-1},"video":null,"audio":null}]}

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2018-10-07 23:04
There is a problem with the CID during transcoding, let me take a look.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2021-05-14 01:17
Fixed in SRS4

**Closed by winlinvip** 2021-05-14 01:17 UTC
Labels: Bug
