### ISSUE TITLE
关于on_publish hook中的stream与参数

### ISSUE THREAD

**Issue by RocFang** [ossrs/srs#1197] opened 2018-08-06 09:37 UTC
hi, @winlinvip 

在 https://github.com/ossrs/srs/commit/85d3a5001c3db244cabad01da2fe3eebb7936925
中http hook的on_publish消息中,对发送的stream值也带了参数,但是考虑到本来已经发送了param,是否这里可以不用在stream中再拼一遍参数呢?

因为考虑到在参数仅为vhost=xxxx的情况下,stream name没有必要拼成stream name+参数的形式,
在on_publish中stream弄成streamname?vhost=xxxx感觉有点怪.

**Comment by RocFang** [comment] 2018-08-07 03:05
For example, rtmp://127.0.0.1/live?vhost=a.com/test
In this format, the stream in the message sent by on_publish will also be concatenated as test?vhost=a.com.

`TRANS_BY_GPT3`

**Comment by RocFang** [comment] 2018-08-07 03:18
This submission is for resolving.
https://github.com/ossrs/srs/commit/a66d450ec1392fab2ef461dff2605e314284acce

However, in srs2.0, there are two forms of parameters, either after the app or after the stream. If both cases exist, then req->param will be overwritten with the form of parameters after the stream with a question mark.

But now, regardless of whether the parameter form is after the app or after the stream, it will be appended to the stream when forwarding at the edge. The mentioned stream value in on_publish is also in this situation.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2018-08-09 00:15
SRS has been a pitfall on the URL for many years, and the root cause lies in my initial lack of understanding of the URI specification.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2018-08-11 02:13
Fixed in https://github.com/ossrs/srs/commit/6cea551c64b09ac840c364fec31f25034a0109c2

**Closed by winlinvip** 2018-08-11 02:13 UTC
Labels: bug
