### ISSUE TITLE
关于局域网本机情况下火狐浏览器localhost地址播放RTC失败

### ISSUE THREAD

**Issue by anglestar2016** [ossrs/srs#2912] opened 2022-02-11 09:00 UTC
关于局域网本机情况下谷歌播放WEBTRTC正常但是火狐失败
问题描述：
1.同样的代码，在谷歌浏览器中，连接局域网部署的视频显示正常，但是在火狐中显示错误（WebRTC: ICE failed, add a STUN server and see about:webrtc for more details）
2.同样的代码，推流至rtmp://r.ossrs.net:1935/live服务器中时，火狐谷歌都显示正常
前端代码：
`</head>
<body>
<video id="rtc_media_player" height="600" width="800" controls autoplay></video>
<script type="text/javascript" src="./js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="./js/srs.sdk.js"></script>
<script>
    $(document).ready(function(){

        $('#rtc_media_player').show();
        let sdk = new SrsRtcPlayerAsync();

        // https://webrtc.org/getting-started/remote-streams
        $('#rtc_media_player').prop('srcObject', sdk.stream);
        // Optional callback, SDK will add track to stream.
        // sdk.ontrack = function (event) { console.log('Got track', event); sdk.stream.addTrack(event.track); };

        // For example: webrtc://r.ossrs.net/live/livestream
        let url = "webrtc://192.168.0.16/live/livestream2022"
        sdk.play(url).then(function(session){
            console.log(session)
        }).catch(function (reason) {
            sdk.close();
            console.error(reason);
        })
    });
</script>
</body>
</html>`
局域网环境以及配置：
1. SRS版本(Version): `4.0.156`
2. SRS的配置如下(Config):
`rtc_server {
    enabled on;
    # Listen at udp://8000
    listen 8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/wiki/v4_CN_RTCWiki#config-candidate
    candidate 192.168.0.16;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}`

重现Bug的步骤
局域网场景
1. `安装srs4.0.156`
2. `不做任何改变，使用“./objs/srs -c conf/rtc.conf”启动项目`
3. `使用OBS推流至局域网服务器`
4. `网页部署在本机tomcat下面，地址：http://localhost:8080/rtc/`
5. 在谷歌中使用localhost访问，视频显示正常，但是在火狐中显示失败
r.ossrs.net场景
1. `使用OBS推流至r.ossrs.net服务器`
2. `网页部署在本机tomcat下面，地址：http://localhost:8080/rtc/`
3. 在谷歌或者火狐中使用localhost访问，视频显示正常
**期望行为(Expect)**
我想知道r.ossrs.net环境中使用的配置是否和我的配置不一致导致系统显示不正常，还是需要在服务器中重新配置别的环境

**Comment by winlinvip** [comment] 2022-02-12 00:49
Try the latest version, 4.0.241. Big brother, 70 versions have passed and you still haven't updated...

`TRANS_BY_GPT3`

**Comment by anglestar2016** [comment] 2022-02-14 09:16
Hello, my current version is 4.0.241, but I still can't play.
The error reason is consistent: WebRTC: ICE failed, add a STUN server and see about:webrtc for more details.
Configuration and files:
[rtc.txt](https://github.com/ossrs/srs/files/8059424/rtc.txt)
Back-end log file.
[srs.log](https://github.com/ossrs/srs/files/8059425/srs.log)
Front-end log screenshot
![Front-end log](https://user-images.githubusercontent.com/31506182/153834868-20a69cb7-0c4c-46c7-91ed-5dfd67bd9f6f.png)




`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2022-02-15 01:18
Your reproduction path is streaming to a public server, but you are playing from a local path. You provided a bunch of information, but it is inconsistent and the problem description is confusing and unreadable.

`TRANS_BY_GPT3`

**Comment by anglestar2016** [comment] 2022-02-16 01:30
Hello, it's like this.
**First logic:**
1. Deploy SRS 4.0.241 in the local area network, with the address 192.168.0.16.
2. The logic code is a local Tomcat or a single page created using WebStorm to play videos. The URL address is webrtc://192.168.0.16/live/livestream2022.
3. The Tomcat playback address is http://localhost:8080/rtc/.
4. Use OBS to stream to the server at 192.168.0.16, and then play the video on the webpage. It does not work properly in Firefox.
**Second logic:**
1. Change the video server to r.ossrs.net.
2. The logic code remains the same as above, with the URL address webrtc://r.ossrs.net/live/livestream2022.
3. The Tomcat playback address is http://localhost:8080/rtc/.
4. Use OBS to stream to the r.ossrs.net server, and then play the video on the webpage. It works properly in Firefox.
**What I think:**
The abnormal display may be due to the different configurations used in the r.ossrs.net environment compared to my configuration. It may be necessary to reconfigure a different environment on the server, or it could be due to other reasons.


`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2022-02-18 03:52
Can the one that comes with SRS work properly? After installing SRS, port 8080 is already open, so there is no need to set up another tomcat.

Please provide the simplest reproduction path. The reproduction path doesn't need to be extensive, the key is to keep it simple and remove any unnecessary information.

1. Install and start SRS.
2. Open localhost:8080 on your local machine.
3. Is WebRTC working properly?

This is the simplest reproduction path.

`TRANS_BY_GPT3`

**Comment by anglestar2016** [comment] 2022-02-23 09:47
In the Centos interface environment test results
Error result: TypeError: self.pc.addTransceiver is not a function
![1](https://user-images.githubusercontent.com/31506182/155294740-e57009e6-e17d-4185-9e0c-e99c5d5935cb.png)
External testing in a virtual machine:
![23](https://user-images.githubusercontent.com/31506182/155295007-7c50786a-435f-4198-be6b-84b65597e490.png)
Streaming environment
![24](https://user-images.githubusercontent.com/31506182/155295071-47cb6194-6c40-4a52-831a-91dfc215d324.png)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2022-02-25 23:58
It seems to be a compatibility issue with Firefox's API. Have you upgraded your Firefox?

`TRANS_BY_GPT3`

**Comment by anglestar2016** [comment] 2022-02-28 01:56
1. The version of Firefox in the CentOS 7 virtual machine is Firefox ESR 52.7.0 (64-bit), which failed the test. It was updated to the latest version, Mozilla Firefox 91.6.0esr, and the system test passed!
2. If virtual machine mapping is done, the port address is mapped to the Windows system, and Firefox 97.0.1 (64-bit) is used to view the following address: http://localhost:8081/players/rtc_player.html?schema=http&port=8081&api=8081. This address plays correctly in Google Chrome, but Firefox throws an error.
![5](https://user-images.githubusercontent.com/31506182/155911681-d8d1623d-89b9-4c04-9f74-3ee6eb821826.png)






`TRANS_BY_GPT3`

**Comment by anglestar2016** [comment] 2022-02-28 02:45
If virtual machine mapping is done to map the port address to the Windows system, use Firefox 91.6.0esr (64-bit) to view and play using the following address: [http://localhost:8081/players/rtc_player.html?schema=http&port=8081&api=8081](http://localhost:8081/players/rtc_player.html?schema=http&port=8081&api=8081). 
While it plays normally in Google Chrome, there is an error in Firefox.
![6](https://user-images.githubusercontent.com/31506182/155915556-2ce22a6c-3146-4819-92c0-9afd98ca4d78.png)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2022-03-05 10:00
👍 Thank you, it seems to be a browser issue that can be resolved by upgrading, so please everyone upgrade.

`TRANS_BY_GPT3`

**Closed by winlinvip** 2022-03-05 10:00 UTC

**Comment by ranxiaoli** [comment] 2022-07-25 05:47
How to solve it? Upgrade the Firefox browser? Why is it that I have the latest version of Firefox, but still encounter this problem?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2022-12-25 05:40
SRS only guarantees compatibility with Chrome and can only strive to ensure compatibility with other browsers. If you want to support Firefox, please provide a patch.

`TRANS_BY_GPT3`

**Comment by sdoeringNew** [comment] 2023-12-08 15:31
Just tested...
SRS 6.0.101 works with Firefox 119.
Just make sure, the CANDIDATE address is **_NOT_** ``localhost``. I simply use the eth0 address and the video plays.
