### ISSUE TITLE
RTMP: Streams failing with `ERROR_RTMP_PACKET_SIZE` error.

### ISSUE THREAD

**Issue by rsravanreddy** [ossrs/srs#2523] opened 2021-08-11 04:31 UTC
**Description**'

Please ensure that the markdown structure is maintained.

We observed for a significant number of the streams the size changes for fmt1 message after fmt0 message resulting  in `ERROR_RTMP_PACKET_SIZE `  and eventually the stream is disconnected. We have observed this from different versions of OBS with RTMP.

Code pointer:
https://github.com/ossrs/srs/blob/4.0release/trunk/src/protocol/srs_rtmp_stack.cpp#L1138

1. SRS Version: `xxxxxx`'

Please ensure that the markdown structure is maintained.
Latest version 

1. SRS Log:
Please ensure that the markdown structure is maintained.
```2013, "msg in chunk cache, size=154678 cannot change to 134574```

1. SRS Configuration:
Please ensure that the markdown structure is maintained.

**Replay**:
Please ensure that the markdown structure is maintained.
1% of the streams from OBS experience this issue

**Expect**:
Please ensure that the markdown structure is maintained.
We are trying to validate the spec if this is expected in RTMP, we have observed in other implementations this case is not explicitly handled.

https://github.com/Red5/red5-server-common/blob/c979950c3b5cd7137303ea2a119af2b9847bed7d/src/main/java/org/red5/server/net/rtmp/codec/RTMPProtocolDecoder.java#L419
https://github.com/Red5/red5-server-common/blob/c979950c3b5cd7137303ea2a119af2b9847bed7d/src/main/java/org/red5/server/net/rtmp/message/Packet.java#L72

Any help here is appreciated, we have tried updating the length and resizing the buffer but bytes were not aligned with the subsequent messages and we saw the data was corrupted.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2021-08-18 00:01
The size of message should be fixed. Which size we should use, the one in fmt0 or fmt1? 

However, you could remove the error and just print a warning like this:

```
            // for a message, if msg exists in cache, the size must not changed.
            // always use the actual msg size to compare, for the cache payload length can changed,
            // for the fmt type1(stream_id not changed), user can change the payload
            // length(it's not allowed in the continue chunks).
            if (!is_first_chunk_of_msg && chunk->header.payload_length != payload_length) {
                srs_warn(ERROR_RTMP_PACKET_SIZE, "msg in chunk cache, size=%d cannot change to %d", chunk->header.payload_length, payload_length);
            }
```

Does it works?

**Comment by winlinvip** [comment] 2024-04-25 23:57
To fix this issue, we need to reproduce it, publishing by a special content with incorrect chunk data. However, I can't reproduce it, so I close it for now.

**Closed by winlinvip** 2024-04-25 23:57 UTC
Labels: Bug, TransByAI
