### ISSUE TITLE
WebRTC: Failed to publish or play the stream immediately. wetrtc streaming and playback both crash.

### ISSUE THREAD

**Issue by zhangyong7887** [ossrs/srs#3173] opened 2022-09-09 07:43 UTC
**Description**
When opening the streaming page on the web, the camera immediately exits after seeing the image. Debugging with web development tools reveals the following errors:
Request URL: https://x.x.x.x:8029/rtc/v1/publish/
Request Method: POST
Status Code: 404 Not Found
The same crash occurs during playback:
Request URL: https://x.x.x.x:8029/rtc/v1/play/
Request Method: POST
Status Code: 404 Not Found
Remote Address: 39.105.209.227:8029
Referrer Policy: strict-origin-when-cross-origin

**SRS Version**
Version: XCORE-SRS/5.0.56(Bee)

**SRS Log**
Log:

```
[2022-09-09 15:34:21.270][Error][7138][6v9g6413][0] serve error code=3009 : parse message : parse message : parse 6528B, nparsed=0, err=16/HPE_INVALID_METHOD invalid HTTP method
thread [7138][6v9g6413]: process_requests() [src/app/srs_app_http_conn.cpp:182][errno=0]
thread [7138][6v9g6413]: parse_message() [src/protocol/srs_protocol_http_conn.cpp:98][errno=0]
thread [7138][6v9g6413]: parse_message_imp() [src/protocol/srs_protocol_http_conn.cpp:130][errno=0]
```

**1. SRS Config**
Config:

```
# SRT config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

#http_api {
#    enabled         on;
#    listen          1985;
#}

http_server {
    enabled         on;
    listen          8028;
    dir             ./objs/nginx/html;
    https {
        enabled         on;
        listen  8029;
        key      /etc/ssl/certs/key.pem;
        cert     /etc/ssl/certs/cert.pem;
    }
}

http_api {
        enabled on;
        listen  1985;
        https {
                enabled on;
                listen  443;
                key      /etc/ssl/certs/key.pem;
                cert     /etc/ssl/certs/cert.pem;

        }
}

rtc_server {
        enabled on;
        listen  8030;
**        candidate       x.x.x.x; #$CANDIDATE; The configured IP is for external network**
}

srt_server {
    enabled on;
    listen 10080;
    maxbw 1000000000;
    connect_timeout 4000;
    peerlatency 0;
    recvlatency 0;
    latency 0;
    tsbpdmode off;
    tlpktdrop off;
    sendbuf 2000000;
    recvbuf 2000000;
}

# @doc https://github.com/ossrs/srs/issues/1147#issuecomment-577607026
vhost __defaultVhost__ {
    #srt {
    #    enabled     on;
    #    srt_to_rtmp on;
    #}

    rtc {
        enabled on;
        bframe  discard;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

# For SRT to use vhost.
vhost srs.srt.com.cn {
}

stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
```

**Replay (重现)**

**可以一直重现该问题**

*Can consistently reproduce the issue*

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**Expect (Expected Behavior)**

> Please describe your expectation (Describe what you expect to happen)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2022-09-16 02:53
No reproduction path? Also, please try the latest 5.0.

`TRANS_BY_GPT3`

**Comment by chenzhu005774** [comment] 2022-10-14 04:09
I also encountered it, it happened when requesting SDP.

`TRANS_BY_GPT3`

**Comment by chenzhu005774** [comment] 2022-10-14 05:06
It is because the VPN on the mobile network was turned on.

`TRANS_BY_GPT3`

**Comment by yipeng2001** [comment] 2023-01-02 04:06
I also encountered this issue. If the address is written incorrectly during the streaming, the error occurs. This is the error log, exactly the same. How can I resolve it?
 [2023-01-02 11:51:49.605][Trace][39858][n4i287k9] TCP: before dispose resource(HttpStream)(0x555555f589f0), conns=5, zombies=0, ign=0, inz=0, ind=0
[2023-01-02 11:51:49.605][Error][39858][n4i287k9][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [39858][n4i287k9]: process_requests() [src/app/srs_app_http_conn.cpp:185][errno=62]
thread [39858][n4i287k9]: parse_message() [src/protocol/srs_service_http_conn.cpp:98][errno=62]
thread [39858][n4i287k9]: parse_message_imp() [src/protocol/srs_service_http_conn.cpp:161][errno=62]
thread [39858][n4i287k9]: grow() [src/protocol/srs_protocol_stream.cpp:162][errno=62]
thread [39858][n4i287k9]: read() [src/protocol/srs_service_st.cpp:522][errno=62](Timer expired)
[2023-01-02 11:51:49.605][Trace][39858][1625393o] TCP: clear zombies=1 resources, conns=5, removing=0, unsubs=0
[2023-01-02 11:51:49.605][Trace][39858][n4i287k9] TCP: disposing #0 resource(HttpStream)(0x555555f589f0), conns=5, disposing=1, zombies=0
[2023-01-02 11:51:49.611][Trace][39858][h074fp69] TCP: before dispose resource(HttpStream)(0x555555f57400), conns=4, zombies=0, ign=0, inz=0, ind=0

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2023-01-02 11:42
Chrome console show these errors, won't fix it.

In the Chrome browser's console, you can see these types of errors. The problem is not in SRS, so SRS cannot fix it.

`TRANS_BY_GPT3`

**Closed as completed by winlinvip** 2023-01-02 11:42 UTC
Labels: WebRTC, Won't fix, TransByAI
