### ISSUE TITLE
webrtc playback intermittent stuttering problem

### ISSUE THREAD

**Issue by joysun2006** [ossrs/srs#2244] opened 2021-03-17 07:39 UTC
**Description**'

Please ensure that the markdown structure is maintained.

SRS Version: 4.0.84'

Please ensure that the markdown structure is maintained.

Test network: Within the school campus network, equivalent to a local area network.

Please ensure that the markdown structure is maintained.

OBS streaming, x264 encoder, RTMP streaming, using official WebRTC configuration, playing with Chrome player. It was observed that there were occasional stutters. Through Chrome's WebRTC debugging, it was found that there was an increase in NACK and PLI packets during the stutters. No stutters were observed during simultaneous FLV playback.

Please ensure that the markdown structure is maintained.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2024-04-23 23:13
Close this issue because lack of description especially the steps to reproduce this issue, please refer to not only #2667, but also to #3861

**Closed as completed by winlinvip** 2024-04-23 23:13 UTC
Labels: TransByAI
