### ISSUE TITLE
一段时间后hls会出现不切片情况

### ISSUE THREAD

**Issue by stevexk** [ossrs/srs#526] opened 2015-11-13 08:33 UTC
原始流是h264+pcmu，使用转码转成h264+aac，然后hls切片。
但是发现一段时间后，（时间不固定，可能很快，也可能要一段时间）hls 切片就不再生成ts.
而此时ffmpeg转码进程还在，转码输入输出流播放都正常。
重启srs之后可能会恢复切片，但是过一段时间后又会出现停止的情况。
看不到明显的日志，只有一段疑是日志，可能和NALU有关，
[2015-11-13 16:14:41.069][trace][21171][1213] start publish mr=0/350, p1stpt=20000, pnt=20000, tcp_nodelay=0, rtcid=1214
[2015-11-13 16:14:41.112][trace][21171][1213] got metadata, width=1280, height=720, vcodec=7, acodec=10
[2015-11-13 16:14:41.112][trace][21171][1213] 30B video sh,  codec(7, profile=Main, level=3.1, 1536x1280, 0kbps, 0fps, 0s)
[2015-11-13 16:14:41.112][trace][21171][1213] 4B audio sh, codec(10, profile=LC, 1channels, 0kbps, 44100HZ), flv(16bits, 2channels, 44100HZ)
[2015-11-13 16:14:41.113][warn][21171][1213][11] hls timestamp jump 1677420=>6210
[2015-11-13 16:14:41.113][error][21171][1213][11] avc decode NALU data failed. ret=3001(Resource temporarily unavailable)
[2015-11-13 16:14:41.113][error][21171][1213][11] hls codec demux video failed. ret=3001(Resource temporarily unavailable)
[2015-11-13 16:14:41.113][warn][21171][1213][11] hls process video message failed, ignore and disable hls. ret=3001
[2015-11-13 16:14:41.648][trace][21171][149] 30B video sh,  codec(7, profile=Main, level=3.1, 1536x1280, 0kbps, 0fps, 0s)
[2015-11-13 16:14:43.618][trace][21171][149] 30B video sh,  codec(7, profile=Main, level=3.1, 1536x1280, 0kbps, 0fps, 0s)
[2015-11-13 16:14:44.199][trace][21171][1213] dvr stream 2113815941_ff to file /mnt/flvs/live/2113815941_ff/2015-11-13_16/14.flv
[2015-11-13 16:14:45.045][trace][21171][172] <- CPB time=2639532, okbps=0,0,0, ikbps=137,122,122, mr=0/350, p1stpt=20000, pnt=20000
[2015-11-13 16:14:45.692][trace][21171][149] 30B video sh,  codec(7, profile=Main, level=3.1, 1536x1280, 0kbps, 0fps, 0s)

**Comment by stevexk** [comment] 2015-11-13 08:34
release of SRS 2.0a2 version

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2015-11-13 08:39
Errors in the log:

'
Please ensure that the markdown structure is maintained.
```
[2015-11-13 16:14:41.113][error][21171][1213][11] avc decode NALU data failed. ret=3001(Resource temporarily unavailable)
```


Failed to parse NALU, please record the RTMP stream and provide a link on the cloud drive.

Please make sure to maintain the markdown structure.

`TRANS_BY_GPT3`

**Comment by stevexk** [comment] 2015-11-13 08:47
Link: http://pan.baidu.com/s/1o6zTMC6 Password: v9rb
The ff extension is after converting to aac.

`TRANS_BY_GPT3`

**Comment by stevexk** [comment] 2015-12-03 09:11
Testing found that it is not related to the NALU error mentioned above, but rather to the network of the pusher. If the pusher's network is unstable and goes offline for a short period before coming back online, it will cause the HLS slicing to stop. Furthermore, it will not resume slicing even if the stream is pushed again after waiting for a long time. The only solution is to restart SRS to restore it.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2015-12-04 03:05
This could be the reason why recv is blocked. Try to find a way to determine the steps to reproduce it, so that it can be fixed once it is reproduced.

`TRANS_BY_GPT3`

**Comment by stevexk** [comment] 2015-12-04 07:27
Using ffmpeg to simulate disconnection cannot be reproduced, but disconnecting the network after streaming with a camera will always reproduce the issue. Comparing the process of establishing an rtmp connection between the two, ffmpeg will send an additional @setDataFrame() message segment, everything else is the same. If the camera has a problem because it did not send this field, why is it normal when initially connected without sending @setDataFrame? Does this field have any impact on hls slicing?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2015-12-04 07:34
:sob: Unplug the network cable :sob:
This is the worst nightmare for all TCP servers. It's not just an issue with SRS, but if you unplug the network cable, the server will inevitably freeze that thread. This is a problem that you can only avoid.
It's a problem with the TCP protocol stack that cannot be avoided at the server level (only through timeouts).

`TRANS_BY_GPT3`

**Comment by stevexk** [comment] 2015-12-04 07:40
It's not about unplugging the SRS server's network cable, but about disconnecting the network of the push end. We need to simulate an unstable camera network, so we can only unplug the network. The network of the SRS server has been normal all along.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2015-12-04 08:33
The client is the same, the server cannot detect disconnection.
You can try other servers, but there is no solution for handling network disconnection.
Simulating an unstable network cannot be done by pulling the network cable.

`TRANS_BY_GPT3`

**Closed** 2015-12-04 08:33 UTC
Labels: bug
