### ISSUE TITLE
PROTOCOL: Replace http-parser for bug and LICENSE

### ISSUE THREAD

**Issue by wanstonq** [ossrs/srs#828] opened 2017-03-31 01:15 UTC
必须是POST /live/live1才行，目录最前必须带有/，否则导致srs程序崩溃

**Comment by wanstonq** [comment] 2017-04-03 09:06
另，如果发送请求的头部没有Transfer-Encoding:chunked，将导致服务器端无法接收消息

**Comment by winlinvip** [comment] 2017-04-15 10:38
Why was it closed?

`TRANS_BY_GPT3`

**Comment by knoxlab** [comment] 2017-04-15 12:29
After actual testing, it was found that if the streaming address does not include "/", SRS will exit abnormally. This is caused by a dead loop in the http parser during parsing.

The reason for the close is that I modified the streaming address and added "/" by default.

However, this should be considered a serious bug and I haven't analyzed how to solve it carefully yet.

Thank you for your reply!

On 2017-04-15 18:38:53, "winlin" <notifications@github.com> wrote:

Why was it closed?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.

`TRANS_BY_GPT3`

**Comment by knoxlab** [comment] 2017-04-15 12:44
Test tool download address: http://pan.baidu.com/s/1o8FBZgm

Video encoding: H.264, audio encoding: AAC, data packaging: flv,
Transmit to server using PowerLive Server.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment] 2017-04-16 07:31
Maybe we should replace the http parser.

**Comment by winlinvip** [comment] 2020-01-25 11:07
Fixed in SRS3: 

```
[2020-01-25 11:06:12.271][Trace][9182][572] HTTP client ip=127.0.0.1, request=0, to=15000ms
[2020-01-25 11:06:21.204][Error][9182][572][11] serve error code=3009 : parse message : parse 26B, nparsed=9, err=7402508/invalid URL 
thread [9182][572]: parse_message() [src/service/srs_service_http_conn.cpp:95][errno=11]
thread [9182][572]: parse_message_imp() [src/service/srs_service_http_conn.cpp:127][errno=11](Resource temporarily unavailable)
```

**Closed by winlinvip** 2020-01-25 11:07 UTC
Labels: bug
