### ISSUE TITLE
Is it possible to support OBS publish HEVC stream over rtmp ?

### ISSUE THREAD

**Issue by cochiachang** [ossrs/srs#3464] opened 2023-03-13 11:28 UTC
## Description

Note that SRS already has HEVC over SRT/HLS/HTTP-TS/WebRTC support, see https://github.com/ossrs/srs/issues/465

1. SRS Version: 6.0.10

2. SRS Log:

```
[2023-03-13 19:13:35.025][INFO][4274][52f90744] RTMP client ip=172.16.50.225:52391, fd=83
[2023-03-13 19:13:35.028][INFO][4274][52f90744] simple handshake success.
[2023-03-13 19:13:35.029][INFO][4274][52f90744] connect app, tcUrl=rtmp://172.16.46.87/live, pageUrl=, swfUrl=rtmp://172.16.46.87/live, schema=rtmp, vhost=172.16.46.87, port=1935, app=live, args=null
[2023-03-13 19:13:35.029][INFO][4274][52f90744] protocol in.buffer=0, in.ack=0, out.ack=0, in.chunk=4096, out.chunk=128
[2023-03-13 19:13:35.103][INFO][4274][52f90744] client identified, type=fmle-publish, vhost=172.16.46.87, app=live, stream=test, param=, duration=0ms
[2023-03-13 19:13:35.103][INFO][4274][52f90744] connected stream, tcUrl=rtmp://172.16.46.87/live, pageUrl=, swfUrl=rtmp://172.16.46.87/live, schema=rtmp, vhost=__defaultVhost__, port=1935, app=live, stream=test, param=, args=null
[2023-03-13 19:13:35.103][INFO][4274][52f90744] source url=/live/test, ip=172.16.50.225, cache=1/2500, is_edge=0, source_id=/im03rm66
[2023-03-13 19:13:35.161][INFO][4274][52f90744] RTC bridge from RTMP, rtmp2rtc=0, keep_bframe=0, merge_nalus=0
[2023-03-13 19:13:35.162][INFO][4274][52f90744] hls: win=60000ms, frag=10000ms, prefix=, path=./objs/nginx/html, m3u8=[app]/[stream].m3u8, ts=[app]/[stream]-[seq].ts, aof=2.00, floor=0, clean=1, waitk=1, dispose=0ms, dts_directly=1
[2023-03-13 19:13:35.162][INFO][4274][52f90744] ignore disabled exec for vhost=__defaultVhost__
[2023-03-13 19:13:35.162][INFO][4274][52f90744] start publish mr=0/350, p1stpt=20000, pnt=5000, tcp_nodelay=0
[2023-03-13 19:13:35.208][INFO][4274][52f90744] got metadata, width=800, height=450, vcodec=7, acodec=10
[2023-03-13 19:13:35.530][INFO][4274][52f90744] 7B audio sh, codec(10, profile=LC, 2channels, 0kbps, 48000HZ), flv(16bits, 2channels, 44100HZ)
```

3. SRS Config:

same as `hevc.flv.conf`

## Replay

Step 1: Publish stream from OBS v29.0.2, and select encoder QuickSync HEVC
![obs setting](http://claire-chang.com/wp-content/uploads/2023/03/2023-03-13_192218.jpg)

Step 2: Start Streaming to SRS server

Step 3: SRS console can see this stream but can not get stream type, and can not play

![console](http://claire-chang.com/wp-content/uploads/2023/03/2023-03-13_191345.jpg)

## Expect

I can see HEVC format video in srs v6.0.10 from publish stream by ffmpeg, but can not see stream if publish from OBS, and I can publish HEVC format by OBS to youtube, and it is normal.
I expect to use OBS to stream in SRS should also be able to play.

**Comment by winlinvip** [comment] 2023-03-14 00:05
Make sense! Could you please join the [discord](https://discord.gg/yZ4BnPmHAd) and we need some help from you, about the environment setup.

**Comment by GekkaSaori** [comment] 2023-03-14 04:02
Encountered the same problem recently with SRS 6.0.34.

It seems like SRS currently only supports push HEVC stream with OBS through SRT[(ref)](https://github.com/ossrs/srs/issues/465#status-of-hevc-in-srs). SRT protocol is supported by VLC, ffplay and ffmpeg. Tested yesterday with OBS and ffplay through SRT and it works(config file: ``srt.conf``). Not tested with other players yet but it **should** works.

Strangely, the cofig flies ``hevc.flv.conf`` or ``hevc.ts.conf`` won't work. In the summary we get no video stream but only audio stream. At the same time, I also get many warning messages from SRS as below:

![image](https://user-images.githubusercontent.com/19746684/224889173-3326e5d2-9da3-474a-b29c-e3716a735dad.png)
It seems like the server did not get correct sequence header, and for ffplay of the client, it just stucks as it didn't receive correct stream information.

**Comment by winlinvip** [comment] 2023-03-20 03:38
For H.265/HEVC over RTMP, OBS use `codecid=7` which is for H.264/AVC codec.

![image](https://user-images.githubusercontent.com/2777660/226240864-af22350e-cd1c-480c-9289-5e3fb04440b3.png)

[obs-rtmp-hevc.pcapng.zip](https://github.com/ossrs/srs/files/11013451/obs-rtmp-hevc.pcapng.zip)

If OBS will use `codecid=7` for both HEVC/AVC, SRS can parse the codec information from NALUs. But it's not normal solution, so I need to confirm with OBS community.

**Comment by winlinvip** [comment] 2023-03-20 04:10
Replied by OBS:

> Matt | WizardCM — Today at 11:45 AM

> If it's silently falling back to a supported codec on the same encoder, that sounds correct while not ideal. I believe there are plans to improve that experience in RFCs?

So seems OBS will remove this feature in future.

**Comment by cochiachang** [comment] 2023-03-20 07:20
> 



> 最近在使用 SRS 6.0.34 時遇到了同樣的問題。
> 
> 似乎 SRS 目前僅支持通過 SRT [(ref)](https://github.com/ossrs/srs/issues/465#status-of-hevc-in-srs)使用 OBS 推送 HEVC 流。VLC、ffplay 和 ffmpeg 支持 SRT 協議。昨天通過 SRT 使用 OBS 和 ffplay 進行了測試，它可以工作（配置文件：）`srt.conf`。尚未與其他播放器一起測試，但**應該**可以。
> 
> 奇怪的是，cofig 會運行`hevc.flv.conf`或`hevc.ts.conf`無法運行。在總結中，我們沒有得到視頻流，只有音頻流。同時，我也收到很多來自SRS的警告信息如下：
> 
> ![圖像](https://user-images.githubusercontent.com/19746684/224889173-3326e5d2-9da3-474a-b29c-e3716a735dad.png) 看起來服務器沒有得到正確的序列頭，對於客戶端的 ffplay，它只是卡住了，因為它沒有收到正確的流信息。

are you sure OBS HEVC via SRT is work?
I use SRS v6.0.10 with srt.conf, and it also failed with OBS in HEVC format
Encoder: QuickSync HEVC
![](http://claire-chang.com/wp-content/uploads/2023/03/2023-03-20_151759.jpg)
Encoder: QuickSync H.264
![](http://claire-chang.com/wp-content/uploads/2023/03/2023-03-20_151722.jpg)

**Comment by cochiachang** [comment] 2023-03-20 09:30
oh...PUSH HEVC over SRT by OBS. supprt after 6.0.20. (https://github.com/ossrs/srs/pull/3366)
I will upgrade my srs version

**Comment by flying1314** [comment] 2023-03-28 13:23
OBS will support AV1、HEVC over RTMP, see this PR, it has been merged, and will be released in OBS 29.1
https://github.com/obsproject/obs-studio/pull/8522

**Comment by flying1314** [comment] 2023-03-29 11:23
> OBS will support AV1,HEVC over RTMP, see this PR, it has been merged and released in OBS 29.1.beta,you can try it[obsproject/obs-studio#8522

> Replied by OBS:
> 
> > Matt | WizardCM — Today at 11:45 AM
> 
> > If it's silently falling back to a supported codec on the same encoder, that sounds correct while not ideal. I believe there are plans to improve that experience in RFCs?
> 
> So seems OBS will remove this feature in future.

**Comment by winlinvip** [comment] 2023-03-31 02:07
@flying1314 Thanks.

https://github.com/obsproject/obs-studio/pull/8522
Enable AV1, HEVC via RTMP to YouTube #8522

Please note that OBS also support RTMP HEVC in OBS 29.1, so SRS will also follow [this](https://github.com/veovera/enhanced-rtmp) standard.

```text
Video FourCC
AV1 = { 'a', 'v', '0', '1' } 
VP9 = { 'v', 'p', '0', '9' } 
HEVC = { 'h', 'v', 'c', '1' }
```

Captured by wireshark is here: [obs-hevc-rtmp-29.1.pcapng.zip](https://github.com/ossrs/srs/files/11120516/obs-hevc-rtmp-29.1.pcapng.zip)

![rtmp-hevc](https://user-images.githubusercontent.com/2777660/229086503-03d4c886-ac6d-443b-9ca8-945cb6f6c604.png)

SRS will support OBS 29.1 to push HEVC via RTMP, please note that previous verisoned OBS is not supported. 

> Note: Old versions of OBS supported HEVC via RTMP but with bugs, the codecid is duplicated to AVC.

**Comment by cochiachang** [comment] 2023-03-31 07:29
I tried using OBS v29.1, but SRS v6.0.34 still cannot recognize AV1/HEVC via RTMP streams coming from OBS.

**Closed as completed** 2023-04-08 01:18 UTC
Labels: Enhancement, Feature, Codec, EnglishNative

**Comment by wsy** [comment] 2024-07-15 08:29
Hi @winlinvip ,
I'm using OBS30.1.2 to stream over RTMP.
I tried both SRS 5.x and SRS 6.x with both Docker(Ubuntu) and Windows. With all four combinations, I cannot stream QSV HEVC nor NVEnc HEVC.
![image](https://github.com/user-attachments/assets/3cfc7755-846b-42b9-a52d-cf3086eba260)

Is there anything I can do to see what went wrong?

**Comment by Docteh** [comment] 2024-07-15 14:34
I got odd errors with OBS 29.0.2, and so I blindly accepted upgrade to OBS 30.2.0 this version works.
![image](https://github.com/user-attachments/assets/f2e4a7ff-bebd-4b10-ab58-0d007217599a)

publishing with RTMP, NVENC on GTX1080

**Comment by wsy** [comment] 2024-07-16 04:57
> I got odd errors with OBS 29.0.2, and so I blindly accepted upgrade to OBS 30.2.0 this version works. ![image](https://private-user-images.githubusercontent.com/190571/348742685-f2e4a7ff-bebd-4b10-ab58-0d007217599a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDQ3MzMsIm5iZiI6MTcyMTEwNDQzMywicGF0aCI6Ii8xOTA1NzEvMzQ4NzQyNjg1LWYyZTRhN2ZmLWJlYmQtNGIxMC1hYjU4LTBkMDA3MjE3NTk5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNDMzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjllNjQxYTk4MmUxNDYwZmNkYmEyZTljZTUxMTZhODFlM2NhMTc0NmE2NDI1ZWIzYWU5OTgxYTgwYjNiNmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HtPxED2O2wEMmBO6MgnO-cC84gvErQC98806jYNmsq4)
> 
> publishing with RTMP, NVENC on GTX1080

Hi @Docteh ,
I upgraded to OBS30.2.0, and I still cannot use HEVC, nor NVEnc. I have i7 6700k with RTX2080.
Can you please share you detailed configuration? 

I tried with OBS30.1.2 and OBS30.2.0, the results are the same:
|Codec|SRS5.exe|SRS6.exe|SRS5Docker|SRS6Docker|
|:---:|:---:|:---:|:---:|:---:|
|CPU x264|Work|Work|Work|Work|
|QSV H264|Work|Work|Work|Work|
|QSV HEVC|No|No|No|No|
|NVEnc H264|No|No|No|No|
|NVEnc HEVC|No|No|No|No|

In the console log of SRS, there's nothing but regular CPU usage report.
![image](https://github.com/user-attachments/assets/63f5330a-6316-45f5-bac7-608af05ffc04)

**Comment by Docteh** [comment] 2024-07-16 05:28
Not sure what sort of detail you need. When I connect with OBS I see this pop up in the log. The CPU usage updates can cause it to scroll past quickly 
![image](https://github.com/user-attachments/assets/c767d3ff-0022-42c3-b643-e6887c2af535)

This is what OBS is told under Output
![image](https://github.com/user-attachments/assets/58ff3482-b23e-43cf-afea-75709eea89e5)

For config on SRS 6.x I am using [http.ts.live.conf](https://github.com/ossrs/srs/blob/develop/trunk/conf/http.ts.live.conf)

**Comment by wsy** [comment] 2024-07-18 00:15
> Not sure what sort of detail you need. When I connect with OBS I see this pop up in the log. The CPU usage updates can cause it to scroll past quickly 
> 
> ![image](https://github.com/user-attachments/assets/c767d3ff-0022-42c3-b643-e6887c2af535)
> 
> 
> 
> This is what OBS is told under Output
> 
> ![image](https://github.com/user-attachments/assets/58ff3482-b23e-43cf-afea-75709eea89e5)
> 
> 
> 
> For config on SRS 6.x I am using [http.ts.live.conf](https://github.com/ossrs/srs/blob/develop/trunk/conf/http.ts.live.conf)
> 
> 

Hi,
Thanks for your information.
I tried 'http.ts.live.conf' and OBS configuration such as 'CQP' instead of 'VBR', but still no luck.

As of the 'CPU Update' log, it's a 2-line log and it's generated every five seconds. So nothing would slip away.

**Comment by Docteh** [comment] 2024-07-20 21:51
So what does the SRS log show on your end? If its not showing even an RTMP connection, its likely that the problem is within OBS, or maybe a firewall

The mere act of a TCP connection on port 1935, via something like OBS or telnet seems to print something to the log

[2024-07-20 14:48:58.166][INFO][1387][n796b84f] RTMP client ip=127.0.0.1:55166, fd=9

**Comment by wsy** [comment] 2024-07-21 23:43
> If its not showing even an RTMP connection, its likely that the problem is within OBS, or maybe a firewall

I don't think it's firewall problem. Because I can stream with Intel QSV and H264.

> [2024-07-20 14:48:58.166][INFO][1387][n796b84f] RTMP client ip=127.0.0.1:55166, fd=9

I will try to find the log file instead of the console log and see if there's anything related to tcp connection.

**Comment by wsy** [comment] 2024-07-24 08:57
Hi Docteh,
Thanks for your idea. I re-checked my network configuration. It's indeed networking problem.
I can now stream with NVEnc or HEVC. Thanks a lot.
